catalog_product:
    resource:
        path: ../src/Catalog/Product/Presentation/Http/
        namespace: App\Catalog\Product\Presentation\Http
    type: attribute

openapi:
    resource: '@OpenApiBundle/config/routes.php'
